import api from './api.js'

export const registerDeliveryPartner = (form) => api.post('/delivery-partners/register', form)
export const getDeliveryApplicationStatus = (id, email) => api.get(`/delivery-partners/applications/${id}/status`, { params: { email }, skipToast: true })
export const getDeliveryProfile = () => api.get('/delivery-partners/profile')
export const updateDeliveryProfile = (data) => api.patch('/delivery-partners/profile', data)
export const updateDeliveryProfileImage = (data) => api.patch('/delivery-partners/profile/image', data)
export const setAvailability = (availability) => api.patch('/delivery-partners/availability', { availability })
export const getDeliveryDashboard = () => api.get('/delivery-partners/dashboard')
export const getAvailableDeliveries = () => api.get('/delivery-partners/deliveries/available')
export const getActiveDeliveries = () => api.get('/delivery-partners/deliveries/active')
export const getDeliveryHistory = () => api.get('/delivery-partners/deliveries/history')
export const getDeliveryEarnings = () => api.get('/delivery-partners/earnings')
export const acceptDelivery = (id) => api.post(`/deliveries/${id}/accept`)
export const rejectDelivery = (id) => api.post(`/deliveries/${id}/reject`)
export const changeDeliveryStatus = (id, status) => api.patch(`/deliveries/${id}/status`, { status })
export const getAdminPartners = () => api.get('/admin/delivery-partners')
export const getAdminDeliveries = () => api.get('/admin/deliveries')
export const approvePartner = (id, approval_status, admin_notes = '') => api.patch(`/admin/delivery-partners/${id}/approval`, { approval_status, admin_notes })
export const setPartnerStatus = (id, status) => api.patch(`/admin/delivery-partners/${id}/status`, { status })
export const assignPartner = (orderId, delivery_partner_id) => api.post(`/admin/orders/${orderId}/assign-delivery-partner`, { delivery_partner_id })
