import { useCallback, useEffect, useState } from 'react'
import AdminNav from '../components/AdminNav.jsx'
import { apiError } from '../services/api.js'
import { approvePartner, assignPartner, getAdminDeliveries, getAdminOrders, getAdminPartners, setPartnerStatus } from '../services/deliveryApi.js'

export default function AdminDeliveryPartners() {
  const [partners, setPartners] = useState([]); const [deliveries, setDeliveries] = useState([]); const [orders, setOrders] = useState([]); const [filter, setFilter] = useState('all')
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [partnerResponse, deliveryResponse, orderResponse] = await Promise.all([getAdminPartners(), getAdminDeliveries(), getAdminOrders()]); setPartners(partnerResponse.data.data); setDeliveries(deliveryResponse.data.data); setOrders(orderResponse.data.data) } catch (requestError) { setError(apiError(requestError)) } finally { setLoading(false) } }, [])
  // Initial API synchronization belongs to this mounted view.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load() }, [load])
  const action = async (key, request) => { setBusy(key); setError(''); try { await request(); await load() } catch (requestError) { setError(apiError(requestError)) } finally { setBusy('') } }
  const visible = partners.filter(partner => filter === 'all' || partner.approval_status === filter || partner.status === filter)
  const onlinePartners = partners.filter(partner => partner.approval_status === 'approved' && partner.status === 'active' && partner.availability === 'online')

  return <div className="admin-page"><AdminNav /><main className="admin-main"><div className="admin-title"><div><span className="eyebrow">Delivery operations</span><h1>Delivery Management</h1></div><select value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All applications</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select></div>
    {error && <div className="form-error" role="alert">{error} <button className="inline-retry" type="button" onClick={load}>Try again</button></div>}
    {loading ? <div className="delivery-empty">Loading Delivery Management…</div> : <>
      <section><h2>Delivery Partner applications</h2><div className="delivery-list">{visible.length === 0 ? <div className="delivery-empty">No applications match this filter.</div> : visible.map(partner => <article className="card delivery-card" key={partner.id}><div><h3>{partner.full_name}</h3><p>{partner.phone} · {partner.address}</p><p>{partner.has_vehicle === 'yes' ? `${partner.vehicle_type} · ${partner.vehicle_number}` : 'No vehicle'}</p><span className="status-badge">{partner.approval_status} / {partner.status} / {partner.availability}</span></div><div className="delivery-actions">{partner.approval_status === 'pending' && <><button disabled={!!busy} className="btn btn-primary" onClick={() => action(partner.id, () => approvePartner(partner.id, 'approved'))}>Approve</button><button disabled={!!busy} className="btn btn-outline" onClick={() => action(partner.id, () => approvePartner(partner.id, 'rejected'))}>Reject</button></>}{partner.approval_status === 'approved' && <button disabled={!!busy} className="btn btn-outline" onClick={() => action(partner.id, () => setPartnerStatus(partner.id, partner.status === 'suspended' ? 'active' : 'suspended'))}>{partner.status === 'suspended' ? 'Activate' : 'Suspend'}</button>}</div></article>)}</div></section>
      <section><h2>Complete order lifecycle</h2><div className="delivery-list">{orders.length === 0 ? <div className="delivery-empty">No orders yet.</div> : orders.map(order => <article className="card delivery-card" key={order.id}><div><h3>{order.order_number}</h3><p><b>Customer:</b> {order.customer?.full_name || 'Unknown'} · <b>Home Cook:</b> {order.home_cook?.full_name || 'Unknown'}</p><p>{order.items.map(item => `${item.quantity} × ${item.name}`).join(', ')}</p><p><b>Payment:</b> {order.payment_status.replaceAll('_', ' ')}</p>{order.delivery_partner && <p><b>Delivery Partner:</b> {order.delivery_partner.full_name} · {order.delivery_partner.phone}</p>}<span className="status-badge">{order.status.replaceAll('_', ' ')}</span></div></article>)}</div></section>
      <section><h2>Ready & active deliveries</h2><div className="delivery-list">{deliveries.length === 0 ? <div className="delivery-empty">No ready or active deliveries.</div> : deliveries.map(delivery => <article className="card delivery-card" key={delivery.id}><div><h3>{delivery.order?.order_number}</h3><p>{delivery.pickup_address} → {delivery.delivery_address}</p><span className="status-badge">{delivery.status.replaceAll('_', ' ')}</span></div>{delivery.status === 'ready_for_delivery' && <select disabled={!!busy} defaultValue="" onChange={event => event.target.value && action(delivery.id, () => assignPartner(delivery.order_id, event.target.value))}><option value="">Assign online partner…</option>{onlinePartners.map(partner => <option key={partner.id} value={partner.id}>{partner.full_name} · {partner.vehicle_number || 'No vehicle'}</option>)}</select>}</article>)}</div></section>
    </>}
  </main></div>
}
