import { useEffect, useMemo, useState } from 'react'
import AdminLayout from '../components/AdminLayout.jsx'
import { complaintIssueLabel } from '../components/ComplaintForm.jsx'
import api, { apiError, assetUrl } from '../services/api.js'
import './Complaints.css'

const statuses=['All','Pending','In Progress','Resolved','Rejected','Under Review','Approved','Refunded','Replacement Sent']
export default function AdminComplaints(){
  const[complaints,setComplaints]=useState([]);const[selected,setSelected]=useState(null);const[filter,setFilter]=useState('All');const[notes,setNotes]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true)
  const load=()=>api.get('/admin/complaints').then(({data})=>{setComplaints(data.data);setSelected(current=>data.data.find(item=>item.id===current?.id)||data.data[0]||null)}).catch(requestError=>setError(apiError(requestError))).finally(()=>setLoading(false))
  useEffect(load,[]);useEffect(()=>setNotes(selected?.admin_notes||''),[selected])
  const visible=useMemo(()=>complaints.filter(item=>filter==='All'||item.complaint_status.replaceAll('_',' ').toLowerCase()===filter.toLowerCase()),[complaints,filter])
  const update=async(status)=>{setBusy(true);try{const{data}=await api.patch(`/admin/complaints/${selected.id}`,{complaint_status:status,admin_response:notes||null});setComplaints(current=>current.map(item=>item.id===selected.id?data.data:item));setSelected(data.data)}catch(requestError){setError(apiError(requestError))}finally{setBusy(false)}}
  const refund=async(type)=>{let partial_amount=null;if(type==='partial'){const input=window.prompt(`Enter a partial refund below Rs ${Number(selected.order.total).toLocaleString()}:`);if(input===null)return;partial_amount=Number(input);if(!Number.isFinite(partial_amount)||partial_amount<=0)return setError('Enter a valid partial refund amount.')}if(!window.confirm(`Confirm ${type} refund${partial_amount?` of Rs ${partial_amount}`:''}? This uses the mock refund processor.`))return;setBusy(true);try{const{data}=await api.post(`/admin/complaints/${selected.id}/refund`,{refund_type:type,partial_amount,admin_notes:notes||null});setComplaints(current=>current.map(item=>item.id===selected.id?data.data:item));setSelected(data.data)}catch(requestError){setError(apiError(requestError))}finally{setBusy(false)}}
  const replace=async()=>{if(!window.confirm('Create a free replacement order and reserve the required food portions?'))return;setBusy(true);try{const{data}=await api.post(`/admin/complaints/${selected.id}/replacement`,{admin_notes:notes||null});setComplaints(current=>current.map(item=>item.id===selected.id?data.data:item));setSelected(data.data)}catch(requestError){setError(apiError(requestError))}finally{setBusy(false)}}
  return <AdminLayout title="Complaints Management" eyebrow="Refunds and replacements" action={<select className="admin-select" value={filter} onChange={event=>setFilter(event.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select>}>
    {error&&<div className="error-banner">{error}</div>}{loading&&<p>Loading complaints…</p>}<div className="report-stats"><article className="card"><i className="red">!</i><div><strong>{complaints.filter(item=>item.complaint_status==='pending').length}</strong><span>Pending</span></div></article><article className="card"><i className="yellow">⌕</i><div><strong>{complaints.filter(item=>item.complaint_status==='under_review').length}</strong><span>Under review</span></div></article><article className="card"><i className="green">✓</i><div><strong>{complaints.filter(item=>['refunded','replacement_sent'].includes(item.complaint_status)).length}</strong><span>Resolved outcomes</span></div></article></div>
    <div className="admin-complaint-grid"><section className="card admin-complaint-list">{visible.map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>setSelected(item)}><div className="complaint-card-top"><div><strong>#{item.order?.order_number}</strong><h3>{complaintIssueLabel(item.issue_type)}</h3><small>{item.customer?.full_name} · {new Date(item.created_at).toLocaleDateString()}</small></div><span className={`complaint-status ${item.complaint_status.replaceAll('_','-')}`}>{item.complaint_status.replaceAll('_',' ')}</span></div></button>)}{!visible.length&&<div className="admin-empty">No complaints match this filter.</div>}</section>
      <aside className="card admin-complaint-detail">{selected?<><div className="complaint-card-top"><div><span className="eyebrow">Complaint #{selected.id}</span><h2>{complaintIssueLabel(selected.issue_type)}</h2></div><span className={`complaint-status ${selected.complaint_status.replaceAll('_','-')}`}>{selected.complaint_status.replaceAll('_',' ')}</span></div>{selected.evidence_image_url&&<img src={assetUrl(selected.evidence_image_url)} alt="Complaint evidence"/>}<p>{selected.description}</p><dl><div><dt>Submitted by</dt><dd>{selected.submitted_by_name||selected.submitted_by?.full_name}<br/>{(selected.submitted_by_role||selected.submitted_by?.role||'').replaceAll('_',' ')}</dd></div><div><dt>Order</dt><dd>#{selected.order?.order_number}<br/>Rs {Number(selected.order?.total||0).toLocaleString()}</dd></div><div><dt>Food</dt><dd>{selected.order?.items?.map(item=>`${item.quantity} × ${item.name}`).join(', ')}</dd></div><div><dt>Home cook</dt><dd>{selected.cook?.kitchen_name||selected.cook?.full_name||'—'}</dd></div><div><dt>Requested solution</dt><dd>{selected.requested_solution}</dd></div>{selected.refund_amount>0&&<div><dt>Refunded</dt><dd>Rs {Number(selected.refund_amount).toLocaleString()}</dd></div>}</dl><label><strong>Admin response</strong><textarea className="admin-notes" value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Explain the resolution to the user." maxLength="2000"/></label><div className="admin-complaint-actions"><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>update('in_progress')}>In Progress</button><button className="btn btn-forest btn-sm" disabled={busy} onClick={()=>update('resolved')}>Resolve</button><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>update('rejected')}>Reject</button>{selected.submitted_by_role!=='home_cook'&&<><button className="btn btn-primary btn-sm" disabled={busy} onClick={()=>refund('full')}>Full refund</button><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>refund('partial')}>Partial refund</button><button className="btn btn-primary btn-sm" disabled={busy} onClick={replace}>Replacement</button></>}</div></>:<div className="admin-empty">Select a complaint to inspect it.</div>}</aside>
    </div></AdminLayout>
}
