import { useCallback, useEffect, useState } from 'react'
import DeliveryNav from '../components/DeliveryNav.jsx'
import { acceptDelivery, changeDeliveryStatus, getActiveDeliveries, getAvailableDeliveries, getDeliveryDashboard, getDeliveryEarnings, getDeliveryHistory, rejectDelivery, setAvailability } from '../services/deliveryApi.js'

const next = {delivery_assigned:['arrived_at_pickup','Arrived at Pickup'],arrived_at_pickup:['picked_up','Picked Up'],picked_up:['out_for_delivery','Out for Delivery'],out_for_delivery:['delivered','Delivered']}
const money=(v)=>`Rs. ${Number(v||0).toLocaleString()}`
export default function DeliveryDashboard(){
 const [tab,setTab]=useState('overview'),[stats,setStats]=useState({}),[rows,setRows]=useState([]),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setLoading(true);try{const [s,a,x,h,e]=await Promise.all([getDeliveryDashboard(),getAvailableDeliveries(),getActiveDeliveries(),getDeliveryHistory(),getDeliveryEarnings()]);setStats({...s.data.data,earnings:e.data.data});setRows(tab==='available'?a.data.data:tab==='active'?x.data.data:tab==='history'?h.data.data:[])}finally{setLoading(false)}},[tab]);useEffect(()=>{load()},[load])
 const act=async(fn)=>{await fn();await load()}
 return <div className="delivery-shell"><DeliveryNav/><main className="delivery-main"><div className="delivery-title"><div><span className="eyebrow">On the road</span><h1>Delivery Dashboard</h1></div><button className={`availability ${stats.availability==='online'?'online':''}`} onClick={()=>act(()=>setAvailability(stats.availability==='online'?'offline':'online'))}>{stats.availability==='online'?'● Online':'○ Offline'}</button></div><div className="delivery-tabs">{['overview','available','active','history','earnings'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{loading?<div className="delivery-empty">Loading deliveries…</div>:tab==='overview'?<div className="stat-grid">{[['Available',stats.available_deliveries],['Active',stats.active_deliveries],["Today's completed",stats.today_completed],['Total completed',stats.total_completed],["Today's earnings",money(stats.today_earnings)],['Total earnings',money(stats.total_earnings)]].map(x=><article className="card stat-card" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></article>)}</div>:tab==='earnings'?<div className="stat-grid">{[['Today',stats.earnings?.today],['This week',stats.earnings?.weekly],['This month',stats.earnings?.monthly],['All time',stats.earnings?.total]].map(x=><article className="card stat-card" key={x[0]}><small>{x[0]}</small><strong>{money(x[1])}</strong></article>)}</div>:<div className="delivery-list">{!rows.length?<div className="delivery-empty">No {tab} deliveries.</div>:rows.map(d=><article className="card delivery-card" key={d.id}><div><span className="status-badge">{d.status.replaceAll('_',' ')}</span><h3>{d.order?.order_number||d.id}</h3><p><b>Home Cook:</b> {d.home_cook?.full_name||'Home Cook'} · {d.home_cook?.phone}</p><p><b>Pickup:</b> {d.pickup_address}</p><p><b>Customer:</b> {d.customer?.full_name} · {d.customer?.phone}</p><p><b>Deliver to:</b> {d.delivery_address}</p><p><b>Food:</b> {d.order?.items?.map(i=>`${i.quantity} × ${i.name}`).join(', ')}</p><strong>{money(d.delivery_fee)}</strong></div><div className="delivery-actions">{tab==='available'&&<><button className="btn btn-primary" onClick={()=>act(()=>acceptDelivery(d.id))}>Accept Delivery</button>{d.delivery_partner&&<button className="btn btn-outline" onClick={()=>act(()=>rejectDelivery(d.id))}>Reject</button>}</>}{tab==='active'&&next[d.status]&&<button className="btn btn-primary" onClick={()=>act(()=>changeDeliveryStatus(d.id,next[d.status][0]))}>{next[d.status][1]}</button>}</div></article>)}</div>}</main></div>
}
